*Developed By: Robiul Islam
*Date: 07 FEB 2017
*Account Closing validation against ATM card Issue
!PROGRAM ATM.ACC.CLOSE.MSG
    SUBROUTINE ATM.ACC.CLOSE.MSG

    $INSERT GLOBUS.BP I_COMMON
    $INSERT GLOBUS.BP I_EQUATE
    $INSERT GLOBUS.BP I_F.ACCOUNT
    $INSERT BP I_F.ATM.CARD.MGT

    FN.AC = "F.ACCOUNT"
    F.AC = ""
    FN.ATM="F.EB.ATM.CARD.MGT"
    F.ATM=""
    Y.ID=ID.NEW

    CALL OPF(FN.AC,F.AC)
    CALL OPF(FN.ATM,F.ATM)
    CALL F.READ(FN.AC,Y.ID,R.AC.REC,F.AC,Y.ERR)
    CALL GET.LOC.REF('ACCOUNT','AC.ATM.CARD.NUM',Y.AC.ATM.CARD.NUM)
    Y.ATM.CARD.MARK= R.AC.REC<AC.LOCAL.REF,Y.AC.ATM.CARD.NUM>

    IF Y.ATM.CARD.MARK NE "" THEN
        CALL F.READ(FN.ATM,Y.ATM.CARD.MARK,R.ATM.REC,F.ATM,Y.ERR)
        IF R.ATM.REC<EB.ATM19.REQUEST.TYPE> EQ "ISSUE" AND R.ATM.REC<EB.ATM19.CARD.STATUS> EQ "DENIED" THEN

        END ELSE
            ETEXT = "CLOSE ATM CARD BEFORE CLOSEING THE ACCOUNT"
            CALL STORE.END.ERROR
        END
    END

    RETURN

