    SUBROUTINE JBL.CASH.REG.BUILD(ENQ)
!PROGRAM JBL.CASH.REG.BUILD

    $INSERT GLOBUS.BP I_COMMON
    $INSERT GLOBUS.BP I_EQUATE
    $INSERT GLOBUS.BP I_F.TELLER
    $INSERT GLOBUS.BP I_ENQUIRY.COMMON


    ENQ<2,1> = 'TRANSACTION.CODE'
    ENQ<3,1> = 'EQ'
    ENQ<4,1> = '4 5 14 16 32 110 112 114 155 22'


    RETURN
END
