    EQU EB.LOG.MSG.APPLN TO 1,
    EB.LOG.MSG.ROUTINE TO 2,
    EB.LOG.MSG.MODULE TO 3,
    EB.LOG.MSG.FILE.NAME TO 4,
    EB.LOG.MSG.REC.KEY TO 5,
    EB.LOG.MSG.OPERATOR TO 6,
    EB.LOG.MSG.DATE TO 7,
    EB.LOG.MSG.TIME TO 8,
    EB.LOG.MSG.CO.CODE TO 9,
    EB.LOG.MSG.LOG.PARAM TO 10,
    EB.LOG.MSG.LOG.LEVEL TO 11,
    EB.LOG.MSG.DESC TO 12,
    EB.LOG.MSG.DETAILS TO 13
